default:
  input_dir: "data"
  output_dir: "output"
  protein_header_fill: "#A7CDF0"
  protein_rows_fill: "#DDEBF7"
  peptide_header_fill: "#F0CBA8"
  peptide_rows_fill: "#FCE4D6"
  out_xlsx: "aspinwallja-20230825-PI1.xlsx"
